[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    emelianov/modbus-esp8266
    bblanchon/ArduinoJson @ ^6.21.3
    witnessmenow/UniversalTelegramBot

build_flags = 
    -D CORE_DEBUG_LEVEL=0