[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

upload_speed = 921600
monitor_speed = 19200
monitor_encoding = latin1
monitor_filters = hexlify, direct

build_flags = 
    -DBOARD_HAS_PSRAM
lib_deps =
    bblanchon/ArduinoJson @ 6.21.3        ; Forzamos la versión 6 para evitar errores
    witnessmenow/UniversalTelegramBot @ ^1.3.0
    emelianov/modbus-esp8266 @ ^4.1.0