[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 460800
;monitor_speed = 115200

build_flags =
    -Os
    -Wl,--gc-sections
    -ffunction-sections
    -fdata-sections
    -D PIO_FRAMEWORK_ARDUINO_MMU_CACHE16_IRAM48
    -DBOARD_HAS_PSRAM
    -D CONFIG_ARDUINO_LOOP_STACK_SIZE=16384
    -DCONFIG_BT_ENABLED=0
    -DCONFIG_BLUEDROID_ENABLED=0
    -DCONFIG_CLASSIC_BT_ENABLED=0

lib_deps =
    bblanchon/ArduinoJson @ 6.21.3
    emelianov/modbus-esp8266 @ ^4.1.0
    